# Generated by Django 5.2 on 2025-04-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
